export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOAD = "PRODUCT_LOAD";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const PRODUCT_BY_ID_LOADING = "PRODUCT_BY_ID_LOADING";
export const PRODUCT_BY_ID_LOAD = "PRODUCT_BY_ID_LOAD";
export const PRODUCT_BY_ID_ERROR = "PRODUCT_BY_ID_ERROR";
